name: Send email new RSS Feed items	

on:
  rss:
    url: https://rsshub.app/telegram/channel/mitpozezot
    config:
      limit: 10
      force: true
      filterOutputs:
        contentSnippet: true
        link: true

jobs:
  telegram:
    name: Send a telegram message html
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_DUMMY_BOT_TOKEN }}
          format: markdown
          message: |
            ${{on.rss.outputs.contentSnippet}}
           
            [קישור להודעה בערוץ הטלגרם שלנו](${{on.rss.outputs.link}})
