# send from my rssfeed, will look for an active user for testing

name: Send telegram message new RSS Feed items	

on:
  rss:
    url: https://rsshub.app/twitter/user/alerttrade
    config:
      limit: 10
      force: false
      filterOutputs:
        contentSnippet: true
        link: true
        pubDate: true

jobs:
  telegram:
    name: Send a telegram message html
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_ME }}
          token: ${{ secrets.TELEGRAM_DUMMY_BOT_TOKEN }}
          format: markdown
          message: |
            ${{on.rss.outputs.contentSnippet}}
            
            ${{ on.rss.outputs.pubDate }}
           
