name: Send telegram message new RSS Feed items riklin10

on:
  rss:
    url: https://rsshub.app/twitter/user/riklin10
    config:
      active: true
      limit: 3
      force: true
      sort: 
        id: -1
      filterOutputs:
        contentSnippet: true
        link: true
        pubDate: true
        dc:creator: true
      resultsPerWorkFLow: 3

jobs:
  telegram:
    name: Send a telegram message html riklin10
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_ME }}
          token: ${{ secrets.TELEGRAM_DUMMY_BOT_TOKEN }}
          format: markdown
          message: |            
            שמעון ריקלין:
            
            ${{ on.rss.outputs['dc:creator'] }}
            
            ${{on.rss.outputs.contentSnippet}}
            
            ${{ on.rss.outputs.pubDate }}
           
            מקור:
            ${{ on.rss.outputs.link }}
