name: Send telegram message new RSS Feed items 

on:
  rss:
    url: http://www.rssmix.com/u/13062168/rss.xml 
    config:
      active: true
      limit: 50
      force: true
      sort: 
        id: -1
      filterOutputs:
        contentSnippet: true
        link: true
        pubDate: true
        author: true

jobs:
  telegram:
    name: Send a telegram message html 
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_ME }}
          token: ${{ secrets.TELEGRAM_DUMMY_BOT_TOKEN }}
          format: markdown
          message: |            

            🧨 ${{ on.rss.outputs.author }}:
            
            ${{on.rss.outputs.contentSnippet}}
            
            ${{ on.rss.outputs.pubDate }}
           
            מקור:
            ${{ on.rss.outputs.link }}
