name: Send telegram message new RSS Feed items 

on:
  rss:
    url: http://www.rssmix.com/u/13062168/rss.xml 
    config:
      active: true
      limit: 20
      force: false
      #sort: 
        #id: -1
      #filterOutputs:
        #contentSnippet: true
        #link: true
        #pubDate: true
        #dc:creator: true

jobs:
  telegram:
    name: Send a telegram message html 
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_DUMMY_BOT_TOKEN }}
          format: html
          message: |            

            <p>${{ on.rss.outputs.creator }}</p>
            
            <p>${{on.rss.outputs.contentSnippet}}</p>
                       
            <p>מקור:</p>
            <p>${{ on.rss.outputs.link }}</p>
      
      - name: Sleep for 3 seconds
        run: sleep 3s
        shell: bash
