name: Send telegram message new RSS Feed items 

on:
  rss:
    url: http://www.rssmix.com/u/13062168/rss.xml 
    config:
      active: true
      limit: 5
      force: true
      sort: 
        id: -1
      #filterOutputs:
        #contentSnippet: true
        #link: true
        #pubDate: true
        #dc:creator: true

jobs:
  telegram:
    name: Send a telegram message html 
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_ME }}
          token: ${{ secrets.TELEGRAM_DUMMY_BOT_TOKEN }}
          format: html
          message: |            

            ${{ on.rss.outputs.creator }}
            
            ${{on.rss.outputs.contentSnippet}}
            
            ${{ on.rss.outputs.pubDate }}
           
            מקור:
            ${{ on.rss.outputs.link }}
