name: Send a telegram message and tweeet when new post in sub
on:
  reddit:
    url: https://www.reddit.com/r/listentothis/new/
    source: json
    config:
      limit: 1
jobs:
  build:
    name: A job to launch telegram notifications
    runs-on: ubuntu-latest
    steps:
    - name: Send notifications
      id: send_notifications
      uses: danilat/externalized-telegram-notifications-action@master
      with:
        to: ${{ secrets.TELEGRAM_ID_OR_CHANNEL }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        content-url: ${{ on.reddit.outputs.thumbnail }}
        parse_mode: html
