name: Send telegram message new RSS Feed items 
on:
  rss:
    url: https://www.reddit.com/r/listentothis/new
    config:
      active: true
      limit: 1
      force: false
      sort: 
        id: -1
jobs:
  telegram:
    name: Send a telegram message html 
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID_OR_CHANNEL }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          content-url: ${{ on.reddit.outputs.thumbnail }}
          parse_mode: html
                   
      - name: Sleep for 4 seconds
        run: sleep 4s
        shell: bash
