name: Send telegram message new RSS Feed items 

on:
  rss:
    url: http://www.rssmix.com/u/13062168/rss.xml 
    config:
      filter:
        title:
          $not:
            $regex: Re
      active: true
      limit: 25
      force: false
      sort: 
        id: -1
jobs:
  telegram:
    name: Send a telegram message html 
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |            
            <a>${{ on.rss.outputs.creator }}</a>
            
            <a>${{on.rss.outputs.contentSnippet}}</a>
             
            <a>מקור:</a>
            <a>${{ on.rss.outputs.link }}</a> 
                   
      - name: Sleep for 4 seconds
        run: sleep 4s
        shell: bash
