name: Send telegram message new RSS Feed items 

on:
  rss:
    url: http://www.rssmix.com/u/13062168/rss.xml 
    config:
      active: true
      limit: 2
      force: true
      sort: 
        id: -1
      #filterOutputs:
        #contentSnippet: true
        #link: true
        #pubDate: true
        #dc:creator: true

jobs:
  telegram:
    name: Send a telegram message html 
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_ME }}
          token: ${{ secrets.TELEGRAM_DUMMY_BOT_TOKEN }}
          format: html
          message: |            

            <a>${{ on.rss.outputs.creator }}</a>
            
            <a>${{on.rss.outputs.contentSnippet}}</a>
             
            <a>מקור:</a>
            <a>${{ on.rss.outputs.link }}</a> 
                   
      - name: Sleep for 4 seconds
        run: sleep 4s
        shell: bash
