name: Do some tests 

on:
  reddit:
    url: https:www.reddit.com/r/listentothis/new/ 
    config:
      active: true
      limit: 4
      force: true

jobs:
  telegram:
    name: Send a telegram message 
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram photo
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            [Hi there](https://www.pngfind.com/pngs/m/137-1375182_bouncer-github-octodex-github-octocat-hd-png-download.png)
          format: markdown
          
#      - name: Sleep for 4 seconds
#        run: sleep 4s
#        shell: bash
