name: Do some tests 

on:
  rss:
    url: https://rssbox.herokuapp.com/twitter/1136566956/Riklin10?exclude_replies=1 
    config:
      active: false
      limit: 2
      force: true
      sort: 
        id: -1
jobs:
  telegram:
    name: Send a telegram message html 
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram message html
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            <a>TEST</a>
            <a>${{ on.rss.outputs.author }}</a>
            
            <a>${{on.rss.outputs.contentSnippet}}</a>
             
            <a>מקור:</a>
            <a>${{ on.rss.outputs.link }}</a> 
                   
      - name: Sleep for 4 seconds
        run: sleep 4s
        shell: bash
