name: Do some tests 

on:
  rss:
#not shofarot 
    url: https://rssbox.herokuapp.com/twitter/2331117414/CantorsParadise?exclude_replies=1&with_media=1 
    config:
      active: true
      limit: 4
      force: true
      sort: 
        id: -1
jobs:
  telegram:
    name: Send a telegram message 
    runs-on: ubuntu-latest
    steps:    
      - name: Send a telegram photo
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: https://www.pngfind.com/pngs/m/137-1375182_bouncer-github-octodex-github-octocat-hd-png-download.png
          
#      - name: Sleep for 4 seconds
#        run: sleep 4s
#        shell: bash
